services:
  - type: web
    name: crowley
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 5000
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: 6379
        sync: false
      - key: REDIS_PASSWORD
        sync: false
    healthCheckPath: /
    plan: free

